Sprint 3
Pashua85/middle.messenger.praktikum.yandex pull request #4
Opened 2023-01-22 12:40 UTC by Pashua85

- добавлен роутинг
- реализована авторизация и регистрация
- добавлено получение чатов
- реализация передачи и получения сообщений по веб-сокет
- добавлен контроллер модалок

2023-01-22 17:09 UTC, agadoev requested changes
Привет, @Pashua85 

Спасибо за работу. Я отметил те места, которые можно улучшить. Без функционала работы с чатами я принять пока что не могу.

2023-01-22 17:09 UTC, agadoev commented on src/core/api/VSTransport.ts
> +import { EventBus } from '../eventBus';
Наверное файл стоит назвать "WSTransport.ts"

2023-01-22 17:09 UTC, agadoev commented on src/core/api/VSTransport.ts
> +    }, 5000) as unknown as number;
Здесь точно нужно "as unknown as number"?

2023-01-22 17:09 UTC, agadoev commented on src/controllers/chatsController.ts
> +    // });
Закомментированный код в репозитории держать нежелательно. Загрязняет кодовую базу.

2023-01-22 17:09 UTC, agadoev commented on src/controllers/chatsController.ts
> +window.chatsController = controller;
Доступ через глобальный объект window - очень опасная тема, потому что тогда из любой точки программы можно будет изменить свойство chatsController. Советую убрать эту строчку.

2023-01-22 17:09 UTC, agadoev commented on src/controllers/messagesController.ts
> +  private onMessage(id: number, messages: IMessage | IMessage[]) {
Мне не очень понятно разделение на ```IMessage``` и ```IMessage[]```. Что, если оставить только массив?

2023-01-22 17:09 UTC, agadoev commented on src/core/api/HTTPTransport.ts
> +  data?: AnyType;
```suggestion
  data?: unknown;
  headers: Record<string, string>
```

2023-01-22 17:09 UTC, agadoev commented on src/core/api/HTTPTransport.ts
> +}
```suggestion
export type Method =
| 'GET'
| 'POST'
| 'PUT'
| 'DELETE'
| 'PATCH'   
```

union в TS - очень мощный инструмент

2023-01-22 17:09 UTC, agadoev commented on src/interfaces/chatInfo.interface.ts
> +
Файлы лучше называть так: ```IChatInfo```, и убрать ```.interface.``` в середине.

2023-01-22 17:09 UTC, agadoev commented on src/controllers/userController.ts
> +    }
по-хорошему, нужно не просто выводить в консоль, а показывать пользователю информацию о том, что произошла ошибка, хотя бы через ```alert```.

2023-01-22 17:09 UTC, agadoev commented on src/components/chat/chat.ts
> +    });
Я думаю, что этот код можно улучшить, если использовать ```reduce``` вместо ```forEach```. Не обязательно, но попробуй

2023-01-22 17:52 UTC, Pashua85 commented on src/core/api/VSTransport.ts
> +import { EventBus } from '../eventBus';
переименовал

2023-01-22 17:53 UTC, Pashua85 commented on src/core/api/VSTransport.ts
> +    }, 5000) as unknown as number;
убрал

2023-01-22 17:54 UTC, Pashua85 commented on src/controllers/chatsController.ts
> +    // });
убрал

2023-01-22 17:54 UTC, Pashua85 commented on src/controllers/chatsController.ts
> +window.chatsController = controller;
убрал тут и в аналогичном месте

2023-01-22 17:56 UTC, Pashua85 commented on src/controllers/messagesController.ts
> +  private onMessage(id: number, messages: IMessage | IMessage[]) {
оставил только массив, работает

2023-01-22 17:57 UTC, Pashua85 commented on src/core/api/HTTPTransport.ts
> +}
поменял на тип

2023-01-22 17:57 UTC, Pashua85 commented on src/interfaces/chatInfo.interface.ts
> +
переименовал файлы

2023-01-22 17:58 UTC, Pashua85 commented on src/controllers/userController.ts
> +    }
пока поменял на alert, потом добавлю нотификации в проекте

2023-01-22 17:58 UTC, Pashua85 commented on src/components/chat/chat.ts
> +    });
поменял на reduce

2023-02-08 18:17 UTC, agadoev approved these changes
Привет, @Pashua85 

Спасибо за правки, сейчас все ок, работу принимаю, удачи в следующем спринте :)

2023-02-11 10:31 UTC, merged